### ISSUE TITLE
Unexpected input handling: line with no command between two semi-colons

### ISSUE THREAD

**Issue by edgariscoding** [unt-sysprog-team/major-assignment-1#12]
You should think carefully about how you want to handle oddly formatted command lines (e.g., lines with no commands between a semi-colon). In these cases, you may choose to print a warning message and/or execute some subset of the commands. However, in all cases, your shell should continue to execute.

**Comment by edgr-sanchez** [comment]
Added in #18.

**Comment by edgariscoding** [comment]
Added in #18.
